/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
      extend: {
          colors: {
              "surface-container-lowest": "#000000",
              "on-surface": "#e2e3ff",
              "surface-container": "#0e1442",
              "primary-dim": "#15a4ff",
              "on-tertiary-container": "#651469",
              "inverse-surface": "#fbf8ff",
              "on-primary-container": "#00253f",
              "on-primary-fixed": "#000000",
              "primary-fixed": "#2aa7ff",
              "on-secondary-fixed": "#004a23",
              "on-tertiary-fixed-variant": "#702073",
              "secondary-container": "#006d37",
              "error-container": "#9f0519",
              "on-surface-variant": "#a3a8d5",
              "tertiary-fixed": "#fc9df7",
              "surface-container-low": "#080e38",
              "surface-dim": "#05092f",
              "on-tertiary-fixed": "#47004c",
              "on-tertiary": "#702073",
              "primary-container": "#2aa7ff",
              "error-dim": "#d7383b",
              "on-error-container": "#ffa8a3",
              "outline": "#6e739d",
              "secondary-fixed-dim": "#5bef90",
              "on-secondary-container": "#e3ffe4",
              "inverse-on-surface": "#4d527a",
              "on-primary": "#003151",
              "surface-tint": "#5eb4ff",
              "tertiary-dim": "#ec90e9",
              "background": "#05092f",
              "surface-container-high": "#131a4c",
              "tertiary": "#ffb3f9",
              "outline-variant": "#40456c",
              "tertiary-fixed-dim": "#ec90e9",
              "tertiary-container": "#fc9df7",
              "on-background": "#e2e3ff",
              "on-primary-fixed-variant": "#002e4d",
              "on-secondary": "#005f2f",
              "primary": "#5eb4ff",
              "primary-fixed-dim": "#0099f0",
              "on-secondary-fixed-variant": "#006a35",
              "error": "#ff716c",
              "on-error": "#490006",
              "secondary": "#6bfe9c",
              "secondary-fixed": "#6bfe9c",
              "surface-variant": "#182056",
              "secondary-dim": "#5bef90",
              "surface": "#05092f",
              "surface-container-highest": "#182056",
              "surface-bright": "#1e2660",
              "inverse-primary": "#00639e"
          },
          fontFamily: {
              "headline": ["Plus Jakarta Sans"],
              "body": ["Manrope"],
              "label": ["Manrope"]
          },
          borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      },
  },
  plugins: [],
}
