spring.application.name=Nikat Backend

# Neon PostgreSQL connection
spring.datasource.url=${DATABASE_URL:postgresql://neondb_owner:npg_VcTnHmJhoW06@ep-calm-meadow-a106b6xh-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DATABASE_USER:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_VcTnHmJhoW06}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true

# Server
server.port=8080
