-- V3__Add_Shop_Contact_Details.sql
ALTER TABLE shops ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
