spring.application.name=Nikat Backend

# Neon PostgreSQL connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-calm-meadow-a106b6xh-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_VcTnHmJhoW06}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true

# Server
server.port=${PORT:8080}
